apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: samplepolicies.policies.ibm.com
spec:
  group: policies.ibm.com
  names:
    kind: SamplePolicy
    listKind: SamplePolicyList
    plural: samplepolicies
    singular: samplepolicy
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: SamplePolicy is the Schema for the samplepolicies API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SamplePolicySpec defines the desired state of SamplePolicy
          properties:
            labelSelector:
              additionalProperties:
                type: string
              type: object
            maxClusterRoleBindingGroups:
              type: integer
            maxClusterRoleBindingUsers:
              type: integer
            maxRoleBindingGroupsPerNamespace:
              type: integer
            maxRoleBindingUsersPerNamespace:
              type: integer
            namespaceSelector:
              description: Target defines the list of namespaces to include/exclude
              properties:
                exclude:
                  items:
                    type: string
                  type: array
                include:
                  items:
                    type: string
                  type: array
              type: object
            remediationAction:
              description: 'RemediationAction : enforce or inform'
              type: string
            severity:
              description: 'Severity : low, medium or high'
              type: string
          type: object
        status:
          description: SamplePolicyStatus defines the observed state of SamplePolicy
          properties:
            compliant:
              description: ComplianceState shows the state of enforcement
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
