apiVersion: policies.ibm.com/v1alpha1
kind: TrustedNodePolicy
metadata:
  name: example-trustednodepolicy
spec:
  severity: low
  namespaceSelector:
    include: ["default"]
  remediationAction: inform
