apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: trusted-node-policy-controller
rules:
  - apiGroups:
    - policies.ibm.com
    resources:
    - trustednodepolicies
    - trustednodepolicies/status
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - roles
    - clusterroles
    - rolebindings
    - clusterrolebindings
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - namespaces
    - nodes
    verbs:
    - get
    - list
    - watch
