kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trusted-node-policy-controller
subjects:
- kind: ServiceAccount
  name: trusted-node-policy-controller
  namespace: calamari
roleRef:
  kind: ClusterRole
  name: trusted-node-policy-controller
  apiGroup: rbac.authorization.k8s.io
