apiVersion: apps/v1
kind: Deployment
metadata:
  name: trusted-node-policy-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: trusted-node-policy-controller
  template:
    metadata:
      labels:
        name: trusted-node-policy-controller
    spec:
      serviceAccountName: trusted-node-policy-controller
      containers:
        - name: trusted-node-policy-controller
          # Replace this with the built image name
          image: lumjjb/trusted-node-policy-controller
          command:
          - trusted-node-policy-controller
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: default
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "trusted-node-policy-controller"
